/**
 * Global ambient declarations.
 *
 * Les bridges legacy `window.*` (appState, ALL_TX, CATEGORIES, getCatStyle,
 * formatLibelle, hideLoader, panneaux avancés…) ont été supprimés : plus aucun
 * code legacy ne les écrivait ni ne les lisait. L'état global passe par le
 * store module (`public/src/store.ts`) et les contexts React ; les helpers
 * s'importent depuis `utils/*`. Voir docs/ARCH_STATE.md.
 */

// Virtual module generated by vite-plugin-pwa — declare here so TS resolves it
// without requiring `/// <reference types="vite-plugin-pwa/react" />` everywhere.
declare module 'virtual:pwa-register/react' {
  export type RegisterSWOptions = {
    immediate?: boolean;
    onNeedRefresh?: () => void;
    onOfflineReady?: () => void;
    onRegistered?: (r: ServiceWorkerRegistration | undefined) => void;
    onRegisterError?: (error: unknown) => void;
  };
  export function useRegisterSW(options?: RegisterSWOptions): {
    needRefresh: [boolean, (v: boolean) => void];
    offlineReady: [boolean, (v: boolean) => void];
    updateServiceWorker: (reloadPage?: boolean) => Promise<void>;
  };
}

declare global {
  interface Window {
    /** Feature flags exposés au runtime depuis main.ts. */
    FLAGS?: unknown;
    /** Racines React montées par main.ts (clé = id du conteneur DOM). */
    reactRoots?: Record<string, import('react-dom/client').Root>;
  }
}

export {};
