import type { LucideIcon } from 'lucide-react';
import {
  Activity,
  Apple,
  ArrowRightLeft,
  Baby,
  Banknote,
  BatteryCharging,
  Bed,
  Beer,
  Bell,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Bus,
  Cake,
  Calendar,
  Camera,
  Car,
  CarFront,
  Cat,
  Cloud,
  Coffee,
  Coins,
  Cookie,
  CreditCard,
  Cross,
  Dog,
  Droplet,
  Droplets,
  Dumbbell,
  FileText,
  Film,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gem,
  Gift,
  Glasses,
  GraduationCap,
  Hammer,
  HandCoins,
  Headphones,
  HeartPulse,
  HelpCircle,
  Home,
  House,
  Lamp,
  Landmark,
  Laptop,
  Lightbulb,
  Mail,
  Milk,
  Monitor,
  MountainSnow,
  Music,
  Package,
  PaintRoller,
  Palette,
  ParkingCircle,
  PartyPopper,
  Percent,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneTakeoff,
  Plug,
  PlugZap,
  Popcorn,
  Receipt,
  RefreshCw,
  Scale,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkles,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Tent,
  Ticket,
  TrainFront,
  Trees,
  TrendingDown,
  TrendingUp,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Wallet,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react';

/**
 * Icônes Lucide importées nommément pour que le bundler n'embarque que celles-ci.
 * Couvre CATEGORY_ICON_GROUPS (éditeur) et CATEGORY_METADATA (valeurs par défaut) ;
 * tout autre nom est chargé à la demande par <CategoryIcon/>.
 */
export const CATEGORY_ICON_COMPONENTS: Record<string, LucideIcon> = {
  activity: Activity,
  apple: Apple,
  'arrow-right-left': ArrowRightLeft,
  baby: Baby,
  banknote: Banknote,
  'battery-charging': BatteryCharging,
  bed: Bed,
  beer: Beer,
  bell: Bell,
  bike: Bike,
  'book-open': BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  bus: Bus,
  cake: Cake,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  'car-front': CarFront,
  cat: Cat,
  cloud: Cloud,
  coffee: Coffee,
  coins: Coins,
  cookie: Cookie,
  'credit-card': CreditCard,
  cross: Cross,
  dog: Dog,
  droplet: Droplet,
  droplets: Droplets,
  dumbbell: Dumbbell,
  'file-text': FileText,
  film: Film,
  flame: Flame,
  footprints: Footprints,
  fuel: Fuel,
  'gamepad-2': Gamepad2,
  gem: Gem,
  gift: Gift,
  glasses: Glasses,
  'graduation-cap': GraduationCap,
  hammer: Hammer,
  'hand-coins': HandCoins,
  headphones: Headphones,
  'heart-pulse': HeartPulse,
  'help-circle': HelpCircle,
  home: Home,
  house: House,
  lamp: Lamp,
  landmark: Landmark,
  laptop: Laptop,
  lightbulb: Lightbulb,
  mail: Mail,
  milk: Milk,
  monitor: Monitor,
  'mountain-snow': MountainSnow,
  music: Music,
  package: Package,
  'paint-roller': PaintRoller,
  palette: Palette,
  'parking-circle': ParkingCircle,
  'party-popper': PartyPopper,
  percent: Percent,
  phone: Phone,
  'piggy-bank': PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  'plane-takeoff': PlaneTakeoff,
  plug: Plug,
  'plug-zap': PlugZap,
  popcorn: Popcorn,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  scale: Scale,
  shield: Shield,
  ship: Ship,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  snowflake: Snowflake,
  sofa: Sofa,
  sparkles: Sparkles,
  star: Star,
  stethoscope: Stethoscope,
  sun: Sun,
  tag: Tag,
  tent: Tent,
  ticket: Ticket,
  'train-front': TrainFront,
  trees: Trees,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  tv: Tv,
  umbrella: Umbrella,
  user: User,
  users: Users,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  wallet: Wallet,
  watch: Watch,
  wifi: Wifi,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
};
