export const FALLBACK_CATEGORIES: Record<'Dépenses' | 'Revenus', string[]> = {
  Dépenses: [
    'A Catégoriser',
    'Achats shopping autres',
    'Apple Music',
    'Assistance juridique',
    'Assurance crédit Maison Gwen',
    'Assurance crédit Maison Nico',
    'Assurance Extension Gwen',
    'Assurance Extension Nico',
    'Assurance habitation',
    'Assurance voiture',
    'Cantine + Alae + Centre',
    'CFDT Nico',
    'Crédit Extension',
    'Crédit Maison',
    'Crédit Maison ProBTP',
    'Crédit voiture',
    'Eau',
    'EDF',
    'Electricité voiture',
    'Entretien Clim/Chauffage',
    'Entretien voiture + Pneus',
    'Epargne',
    'Extension',
    'Fibre SFR',
    'Frais bancaires',
    'Habits',
    'iCloud',
    'Impots fonciers',
    'Kdo Anniversaire nous 4',
    'Kdos Anniversaires',
    'Mobile Gwen',
    'Mobile Nico',
    'Netflix',
    'Noel Famille',
    'Noels nous 4',
    'Notes de frais',
    'Nourriture',
    'Prime',
    'Renouvellement Electronique/electromenager',
    'Santé',
    'Sorties',
    'Sport',
    'Travaux maison',
    'Vacances Autres',
    'Vacances été (Bretagne)',
    'Vacances Noel (Bretagne)',
    'Vacances Novembre',
    'Vacances ski',
  ],
  Revenus: [
    'Autres revenus',
    'CAF',
    'Prime vacance',
    'Remboursement',
    'Retrait Epargne',
    'Salaire Gwen',
    'Salaire Nico',
    'Virements internes',
  ],
};

/**
 * Catégories du budget (le preset legacy window.CATEGORIES n'existe plus).
 */
export const CATEGORIES: Record<'Dépenses' | 'Revenus', string[]> = {
  Dépenses: [...FALLBACK_CATEGORIES['Dépenses']],
  Revenus: [...FALLBACK_CATEGORIES['Revenus']],
};
